import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/auth-provide";
import { LayoutWrapper } from "@/components/layout-wrapper";

const prompt = Prompt({
  weight: ["300", "400", "500", "700"],
  variable: "--font-prompt-sans",
  subsets: ["latin", "thai"],
});

export const metadata: Metadata = {
  title: "LeftoverChef",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${prompt.variable} antialiased`}>
        <AuthProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
